BookTracker/Controllers/AccountantController.cs
using BookTracker.Models;
using BookTracker.ViewModel;
using BookTracker.ViewModels;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using Newtonsoft.Json;
using System.IO;
using System.Configuration;
using System.Globalization;

namespace BookTracker.Controllers
{
    public class AccountantController : Controller
    {
       private BT_Entity1 db = new BT_Entity1();
        // GET: Accountant


        public ActionResult Index()
        {           
           
            return View();
        }


        public ActionResult Charts()
        {
            return View();
        }

        public ActionResult Entry()
        {
            List<accountsTable> accountsList = db.accountsTables.Where(x => x.acctStateID == 1).ToList();
            ViewBag.ListofAccounts = new SelectList(accountsList, "acctNo", "acctName");
            List<journalTypesTable> journalTypesList = db.journalTypesTables.ToList();
            ViewBag.ListofJournalTypes = new SelectList(journalTypesList, "journalTypeID", "journalType");
            return View();

        }

        #region financial statements
        public ActionResult TrialBalance()
        {
            return View();
        }

        public JsonResult IncomeStatementExpense()
        {
            
            using (db)
            {
                var data = db.accountsTables.Where(a => a.acctCat == 5 && (a.totalDebits != 0 || a.totalCredits != 0)).ToList();


                //data = data.Where(a => a.totalCredits > 0 || a.totalCredits > 0).ToList();

                //List<accountsTable> accounts =
                var col = data.Select(x => new
                {
                   
                    x.acctName,
                    x.totalDebits,
                 

                }).ToList();

                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult IncomeStatementRevenues()
        {
           

            using (db)
            {
                var data = db.accountsTables.Where(a=> a.acctCat == 4 && (a.totalDebits != 0 || a.totalCredits != 0 )).ToList();

                //data = data.Where(a => a.totalCredits > 0 || a.totalCredits > 0).ToList();
                
                //List<accountsTable> accounts =
                var col = data.Select(x => new
                {
                    
                  
                    x.acctName,
                   x.totalCredits

                }).ToList();

                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult IncomeStatementTotals()
        {


            using (db)
            {
                decimal total = 0;
                var revs = db.accountsTables.Where(a => a.acctCat == 4 && a.balance != 0).ToList();
                var exps = db.accountsTables.Where(a => a.acctCat == 5 && a.balance != 0).ToList();
                if(total == 0)
                {
                    foreach (var r in revs)
                    {
                        total -= r.balance;
                    }
                    foreach (var r in exps)
                    {
                        total -= r.balance;
                    }
                }


                var col = revs.Select(x => new
                {
                    total
                }
                );

                //data = data.Where(a => a.totalCredits > 0 || a.totalCredits > 0).ToList();

                //List<accountsTable> accounts =


                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult IncomeStatementTotalT()
        {


            using (db)
            {
                decimal total = 0;
                var revs = db.accountsTables.Where(a => a.acctCat == 4).ToList();
                var exps = db.accountsTables.Where(a => a.acctCat == 5 ).ToList();
                if (total == 0)
                {
                    foreach (var r in revs)
                    {
                        total -= r.balance;
                    }
                    foreach (var r in exps)
                    {
                        total -= r.balance;
                    }
                }


                var col = revs.Select(x => new
                {
                    total
                }
                );

                //data = data.Where(a => a.totalCredits > 0 || a.totalCredits > 0).ToList();

                //List<accountsTable> accounts =


                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult SoRE()
        {
            ViewBag.title = "BookTracker Accountants";
            ViewBag.statement = "Statement of Retained Earnings";
            ViewBag.date = DateTime.Now;

            using (db)
            {
             
                decimal iniBal = 0;
        
                var retEarnings = db.accountsTables.Where(a => a.acctNo == 600).ToList();
                

                foreach (var v in retEarnings)
                {
                    iniBal = v.initialBalace;
                }
                var col = retEarnings.Select(x => new
                {
                  x.initialBalace
                }
                );                      

                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult SoREDeb()
        {
           
            using (db)
            {
                var retEarnings = db.accountsTables.Where(a => a.acctNo == 600).ToList();            
              
                
                var col = retEarnings.Select(x => new
                {
                    x.totalDebits
                }
                );

                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult SoREBal()
        {

            using (db)
            {
                var retEarnings = db.accountsTables.Where(a => a.acctNo == 600).ToList();
                decimal balance = 0;
                foreach (var v in retEarnings)
                {
                    balance = v.initialBalace-v.totalDebits;
                }
                if(balance == 0)
                {
                    decimal total = 0;
                    var revs = db.accountsTables.Where(a => a.acctCat == 4 && a.balance != 0).ToList();
                    var exps = db.accountsTables.Where(a => a.acctCat == 5 && a.balance != 0).ToList();
                    if (total == 0)
                    {
                        foreach (var r in revs)
                        {
                            total -= r.balance;
                        }
                        foreach (var r in exps)
                        {
                            total -= r.balance;
                        }
                    }
                    balance = total;
                }

                var col = retEarnings.Select(x => new
                {
                    balance
                }
                );

                return Json(new { data = col }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult IncomeStatement()
        {
            ViewBag.title = "BookTracker Accountants";
            ViewBag.statement = "Income Statement";
            ViewBag.date = DateTime.Now.Month + DateTime.Now.Year;
            return View();
        }

        public ActionResult BalanceSheet()
        {
            using (db)
            {
                var data = db.accountsTables.Where(a => a.acctCat == 1 && (a.totalDebits != 0 || a.totalCredits != 0)).ToList();
                // var total = "Total Assets";
                var data2 = db.accountsTables.Where(a => (a.acctCat == 2 || a.acctCat == 3 || a.acctNo == 700) && (a.totalDebits != 0 || a.totalCredits != 0)).ToList();

                decimal sumTotal = 0;
                decimal sumTotal2 = 0;
                if (sumTotal == 0)
                {
                    foreach (var i in data)
                    {

                        if (i.totalDebits > i.totalCredits)
                        {
                            sumTotal -= (i.totalDebits - i.totalCredits)*-1;
                            ///sumTotal = totalDebits;
                        }
                        else
                        {
                            sumTotal -= (i.totalDebits - i.totalCredits)*-1;
                            //sumTotal = totalCredits;
                        }
                    }
                }
                ViewBag.sumTotal = sumTotal.ToString("C",CultureInfo.CurrentCulture);
                
                if (sumTotal2 == 0)
                {
                    foreach (var i in data2)
                    {

                        if (i.totalDebits > i.totalCredits)
                        {
                            sumTotal2 += (i.totalDebits - i.totalCredits)*-1;
                            ///sumTotal = totalDebits;
                        }
                        else
                        {
                            sumTotal2 += i.totalCredits - i.totalDebits;
                            //sumTotal = totalCredits;
                        }                    }
                }
                ViewBag.sumTotal2 = sumTotal2.ToString("C", CultureInfo.CurrentCulture);
            }
          
            ViewBag.title = "BookTracker Accountants";
            ViewBag.statement = "Balance Sheet";
            ViewBag.date = DateTime.Now;
            return View();
        }

        public ActionResult StatementOfRetaindEarnings()
        {
            ViewBag.title = "BookTracker Accountants";

BookTracker/Views/Shared/_Accountant.cshtml
@{
    //Author: Sai Pyneni
    //date: 1/27/2019
    Layout = null;
    if (Session["userID"] == null)
    {
        Response.Redirect("~/userTable/Login");
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Tracker</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/BookTracker_logo.ico" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body style="background-color: whitesmoke">

    <nav class="navbar navbar-expand-sm navbar-dark fixed-top " style="background-color: #666; background: #666">
        <a class="navbar-brand">
            <img class="" style="max-height: 70px; max-width: 70px;" src="~/Images/BookTracker_logo.gif" title="BookTracker-logo" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font:bold">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Dashboard", "Index", "Accountant", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Chart Of Accounts", "Charts", "Accountant", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Journal", "Entry", "Accountant", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" style="color: white; font: bold" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Financial Statements
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Trial Balance", "TrialBalance", "Accountant", new { }, new { @class = "nav-link", @style = " color: white" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Income Statement", "IncomeStatement", "Accountant", new { }, new { @class = "nav-link", @style = " color: white" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Balance Sheet", "BalanceSheet", "Accountant", new { }, new { @class = "nav-link ", @style = " color: white" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("State of Retained Earnings", "StatementOfRetaindEarnings", "Accountant", new { }, new { @class = "nav-link ", @style = " color: white" })

                    </div>
                </li>
               

            </ul>
            <div class="nav-item dropdown active bs-popover-right">

                @Html.ActionLink("Log Out", "LogOut", "userTable", new { }, new { @class = "nav-link ", @style = " color: white" })
            </div>

            <h3 style="font-family:OCR A Std; color:white" class="font-weight-bold font-italic"> Hello, @Session["userFName"].ToString()</h3>


            <!--<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form> -->
        </div>

    </nav>

    <div style="padding: 10px">

    </div>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Tracker Application</p>
        </footer>
    </div>

    @RenderSection("Scripts", false)

</body>
</html>

@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/dropzone")

BookTracker/Views/Shared/_Admin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Admin</title>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>
    <div>
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top " style="background-color: #666; background: #666">
            <a class="navbar-brand">
                <img class="" style="max-height: 70px; max-width: 70px;" src="~/Images/BookTracker_logo.gif" title="BookTracker-logo" />
            </a>
            @Html.ActionLink("Book Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand font-weight-bold ", @style = "font-family: OCR A Std" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font:bold">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("User Managment", "Index", "Admin", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Accounts Management", "Index", "ChartOfAccounts", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active text-hide">
                        @Html.ActionLink("Contact", "Contact", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Event Log", "Index", "Eventlog", new { }, new { @class = "nav-link" })
                    </li>

                </ul>
                <div class="nav-item dropdown active bs-popover-right">
                    @Html.ActionLink("Log Out", "LogOut", "userTable", new { }, new { @class = "nav-link ", @style = " color: white" })
                </div>

                <h3 style="font-family:OCR A Std; color:white" class="font-weight-bold font-italic"> Hello, @Session["userFName"].ToString()</h3>

                <!--<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form> -->
            </div>

        </nav>
    </div>
</body>
</html>

BookTracker/Views/Shared/_Layout.cshtml
    @{
        //Author: Sai Pyneni
        //date: 1/27/2019
        Layout = null;
        if(Session["userID"] == null)
        {
            Response.Redirect("~/userTable/Login");
        }
    }

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Tracker</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/BookTracker_logo.ico" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body  style="background-color: whitesmoke">

    <nav class="navbar navbar-expand-sm navbar-dark fixed-top " style="background-color: #666; background: #666">
        <a class="navbar-brand">
            <img class="" style="max-height: 70px; max-width: 70px;" src="~/Images/BookTracker_logo.gif" title="BookTracker-logo" />
        </a>
      
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font:bold">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Admin Dashboard", "Dashboard", "Admin", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("User Management", "Index", "Admin", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Chart Of Accounts", "Index", "ChartOfAccounts", new { }, new { @class = "nav-link" })
                </li>

                <li class="nav-item active">
                    @Html.ActionLink("Event Log", "Index", "Eventlog", new { }, new { @class = "nav-link" })
                </li>

            </ul>
            <div class="nav-item dropdown active bs-popover-right">
                <a class="nav-link dropdown-toggle font-weight-bold" style="color: white; font: bold" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">

                    @Html.ActionLink("Reset Password", "ForgotPassword", "userTable", new { }, new { @class = "nav-link", @style = " color: white" })
                    <div class="dropdown-divider"></div>
                    @Html.ActionLink("Log Out", "LogOut", "userTable", new { }, new { @class = "nav-link ", @style = " color: white" })
                </div>
            </div>

            <h3 style="font-family:OCR A Std; color:white" class="font-weight-bold font-italic"> Hello, @Session["userFName"].ToString()</h3>

            <!--<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form> -->
        </div>

    </nav>

    <div style="padding: 10px">

    </div>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Tracker Application
            
            </p>
        </footer>
    </div>

    @RenderSection("Scripts", false)

</body>
</html>
 
    @Scripts.Render("~/bundles/bootstrap")
  

BookTracker/Views/Shared/_Layout1.cshtml
@{
    ViewBag.Title = "_Layout1";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Tracker</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/BookTracker_logo.ico" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />


</head>


<body>
    <div style="padding: 5px">

    </div>
    <div class="container body-content">
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderBody()
        @Styles.Render("~/Content/ForgotPassword.css")
        @Styles.Render("~/Content/Button.css")

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", false)
      
    </div>

    <footer>

    </footer>
</body>

    
</html>

BookTracker/Views/Shared/_Manager.cshtml
@{
    //Author: Sai Pyneni
    //date: 1/27/2019
    Layout = null;
    if (Session["userID"] == null)
    {
        Response.Redirect("~/userTable/Login");
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Tracker</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/BookTracker_logo.ico" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body style="background-color: whitesmoke">

    <nav class="navbar navbar-expand-sm navbar-dark fixed-top " style="background-color: #666; background: #666">
        <a class="navbar-brand">
            <img class="" style="max-height: 70px; max-width: 70px;" src="~/Images/BookTracker_logo.gif" title="BookTracker-logo" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font:bold">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Dashboard", "Index", "Manager", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Chart Of Accounts", "Charts", "Manager", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Journal", "Journal", "Manager", new { }, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" style="color: white; font: bold" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Financial Statements
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">

                        @Html.ActionLink("Trial Balance", "TrialBalance", "Manager", new { }, new { @class = "nav-link", @style = " color: white" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Income Statement", "IncomeStatement", "Manager", new { }, new { @class = "nav-link", @style = " color: white" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Balance Sheet", "BalanceSheet", "Manager", new { }, new { @class = "nav-link ", @style = " color: white" })

                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("State of Retained Earnings", "StatementOfRetaindEarnings", "Manager", new { }, new { @class = "nav-link ", @style = " color: white" })

                    </div>
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Event Log", "EventLog", "Manager", new { }, new { @class = "nav-link" })
                </li>



            </ul>
            <div class="nav-item dropdown active bs-popover-right">

                @Html.ActionLink("Log Out", "LogOut", "userTable", new { }, new { @class = "nav-link ", @style = " color: white" })
            </div>

            <h3 style="font-family:OCR A Std; color:white" class="font-weight-bold font-italic"> Hello, @Session["userFName"].ToString()</h3>


            <!--<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form> -->
        </div>

    </nav>

    <div style="padding: 10px">

    </div>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Tracker Application</p>
        </footer>
    </div>

    @RenderSection("Scripts", false)

</body>
</html>

@Scripts.Render("~/bundles/bootstrap")